language: php
sudo: false
php:
  - 5.6
  - 7
  - 7.1
  - 7.2
  - 7.3

before_install:
  - composer self-update

install:
  - mkdir -p logs
  - composer require --dev satooshi/php-coveralls
  - composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --coverage-clover logs/clover.xml

after_script:
  - travis_retry vendor/bin/coveralls -v
